### ISSUE TITLE
Updating Options from BC Automatically

### ISSUE THREAD

**Issue by eaf-josephportello** [MicrosoftDocs/dynamics365smb-docs#457] opened 2020-11-07 21:54 UTC
This seems to highlight that the only way to update Payment Terms from BC to the integration table is via a custom extension. 

Can you sync payment terms automatically, if so, how? Is the full extent of how Common Data Services and Dynamics 365 Sale Sync documented cohesively?

Regards

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 642b847f-299f-3489-0db9-44f49b46a8bc
* Version Independent ID: 7eaf5cc4-ce22-026c-4bc6-23ef0e17b2f9
* Content: [Handling Missing Option Values - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/admin-cds-missing-option-values)
* Content Source: [business-central/admin-cds-missing-option-values.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/live/business-central/admin-cds-missing-option-values.md)
* Service: **dynamics365-business-central**
* GitHub Login: @bholtorf
* Microsoft Alias: **bholtorf**

**Comment by edupont04** [comment] 2020-11-10 13:09
Duplicate of #458

**Closed by edupont04** 2020-11-10 13:09 UTC
