### ISSUE TITLE
Generate an XMLport that is based on an XML schema

### ISSUE THREAD

**Issue by beemubotokka** [MicrosoftDocs/dynamics365smb-docs#417] opened 2020-08-24 11:14 UTC
Hi,

This documentation says, that we could save generated XMLport object as an .al file.
Is that possible to do at starting which version?
I have done my test with SaaS version 16.4.14693.15090, but generated file is still .txt file (for C/AL).

Br, Teemu

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 32700315-68a5-7730-ea62-98f7e7ce453f
* Version Independent ID: f9d7f0ec-4728-ad7a-a331-6bcddce2f792
* Content: [Create XMLports based on XML schemas - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/across-how-to-use-xml-schemas-to-prepare-data-exchange-definitions)
* Content Source: [business-central/across-how-to-use-xml-schemas-to-prepare-data-exchange-definitions.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/live/business-central/across-how-to-use-xml-schemas-to-prepare-data-exchange-definitions.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SorenGP
* Microsoft Alias: **sgroespe**

**Comment by brentholtorf** [comment] 2020-08-25 12:03
Duplicate of #415

**Closed by brentholtorf** 2020-08-25 12:03 UTC
Labels: duplicate, question
