### ISSUE TITLE
How to use a Data Exchange Definition

### ISSUE THREAD

**Issue by lvanvugt** [MicrosoftDocs/dynamics365smb-docs#298] opened 2020-02-19 02:50 UTC
Great, with this the current topic ("Set Up Data Exchange Definitions") I know how to setup a Data Exchange Definition. But now, how do I use it?
OK, the various standard feature, like sending electronic documents, that use it are described, but please add a generic topic that tells me how I can use it in a new feature.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 350ad27c-dd1c-fde6-27a3-faaf9c0c3da1
* Version Independent ID: 704d9728-05d0-c21a-9d68-d23af8fc6457
* Content: [Define how data is exchanged electronically - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/across-how-to-set-up-data-exchange-definitions)
* Content Source: [business-central/across-how-to-set-up-data-exchange-definitions.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/live/business-central/across-how-to-set-up-data-exchange-definitions.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SorenGP
* Microsoft Alias: **sgroespe**

**Comment by edupont04** [comment] 2020-07-24 15:55
Duplicate of #296

**Closed by edupont04** 2020-07-24 15:55 UTC
