### ISSUE TITLE
On Get File Structure page ... (step 7  of task "To create a data exchange definition")

### ISSUE THREAD

**Issue by lvanvugt** [MicrosoftDocs/dynamics365smb-docs#297] opened 2020-02-19 02:28 UTC
Here is written:

On the Get File Structure page, select the related structure file, and then choose the OK button. The lines on the Column Definitions FastTab are filled according to the structure of the data file.

But no mentioning that this only applies for XML or JSON. When pressing the "Get File Structure ..." action when defining a Data Exhcnage Definition for FIle Type "Variable Text" an error is show saying: File type Variable Text is not supported.
This might b made explicit.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 350ad27c-dd1c-fde6-27a3-faaf9c0c3da1
* Version Independent ID: 704d9728-05d0-c21a-9d68-d23af8fc6457
* Content: [Define how data is exchanged electronically - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/across-how-to-set-up-data-exchange-definitions)
* Content Source: [business-central/across-how-to-set-up-data-exchange-definitions.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/live/business-central/across-how-to-set-up-data-exchange-definitions.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SorenGP
* Microsoft Alias: **sgroespe**

**Comment by edupont04** [comment] 2020-07-24 15:55
Duplicate of #296

**Closed by edupont04** 2020-07-24 15:55 UTC
