### ISSUE TITLE
From the German Help (de-DE) to Austrian Search (de-AT)?

### ISSUE THREAD

**Issue by DanielGoehler** [MicrosoftDocs/dynamics365smb-docs#70] opened 2018-11-28 20:25 UTC
If I search something in the German Help https://docs.microsoft.com/de-de/dynamics365/business-central/ (de-DE) and I click on _Search the entire Business Central documentation for "something"_ I end up in the 
 Austrian Help with the Search Result: https://docs.microsoft.com/de-at/search/index?search=something&scope=BusinessCentral (de-AT)

**Comment by edupont04** [comment] 2018-11-29 08:14
Hello Daniel,
I'm going to close this issue, not because I want to dismiss your feedback, but because it's not something we can do anything about. Also, I can't reproduce your experience, which is not to say that I don't believe you (I do believe you, actually, but I don't see the same behaviour in my browser).

**Closed by edupont04** 2018-11-29 08:14 UTC
Labels: question
