### ISSUE TITLE
Link towards App Monetization sample code broken

### ISSUE THREAD

**Issue by louagej** [MicrosoftDocs/dynamics365smb-docs#394] opened 2020-06-30 14:37 UTC
Hi,

I'm looking for the App Monetization sample code but link towards https://mbspartner.microsoft.com/secure/coursematerials/D365/Standalone/AppMonetizationDemo.zip isn't available anymore

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ed34ba95-a843-90b0-dd51-c24023ccd9d2
* Version Independent ID: 43259fda-960d-bd7a-97c6-74f569a54e11
* Content: [Developers learning catalog - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/readiness/readiness-learning-developers)
* Content Source: [business-central/readiness/readiness-learning-developers.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/live/business-central/readiness/readiness-learning-developers.md)
* Service: **dynamics365-business-central**
* GitHub Login: @loreleishannonmsft
* Microsoft Alias: **v-lshann**

**Comment by edupont04** [comment] 2020-07-02 14:54
Duplicate of #320 
You can also vote for this suggestion: https://experience.dynamics.com/ideas/idea/?ideaid=8a736a33-0937-ea11-8454-0003ff689f0d

**Closed by edupont04** 2020-07-02 14:54 UTC
