### ISSUE TITLE
Images still display the old naming of DEF

### ISSUE THREAD

**Issue by lvanvugt** [MicrosoftDocs/dynamics365smb-docs#299] opened 2020-02-19 07:30 UTC
The two images on this topic still call DEF "Posting Exchange". This is confusing. Please update.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 633f7be1-2925-08b7-28f2-d4712632a730
* Version Independent ID: 593ffd07-a994-7b69-11a6-385fefcf395a
* Content: [About the Data Exchange Framework - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/across-about-the-data-exchange-framework)
* Content Source: [business-central/across-about-the-data-exchange-framework.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/live/business-central/across-about-the-data-exchange-framework.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SorenGP
* Microsoft Alias: **sgroespe**

**Comment by edupont04** [comment] 2020-07-24 15:54
Duplicate of #296

**Closed by edupont04** 2020-07-24 15:54 UTC
