### ISSUE TITLE
Processing rules

### ISSUE THREAD

**Issue by fvet** [MicrosoftDocs/dynamics365smb-docs#522] opened 2021-03-19 13:24 UTC
I'm missing some information / samples on how to use the 'Processing Rules' on rapidstart packages.
See https://www.navug.com/communities/community-home/digestviewer/viewthread?GroupId=49&MessageKey=75c95752-08dc-480a-94eb-f49ad33559fd&CommunityKey=95503735-5a0b-4af1-8326-9bd7bb3b4d3d&tab=digestviewer

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d0fbb8d7-a830-8b43-664f-e64a9e2109a5
* Version Independent ID: a7206a73-39e4-86e9-774f-fc1121b327b0
* Content: [Tips and Tricks - RapidStart Services - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/admin-tips-and-tricks-rapidstart-services)
* Content Source: [business-central/admin-tips-and-tricks-rapidstart-services.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/live/business-central/admin-tips-and-tricks-rapidstart-services.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SorenGP
* Microsoft Alias: **edupont**

**Comment by edupont04** [comment] 2021-03-23 15:33
Hello,

Thank you for your feedback! Since it is identical to feedback that you submitted for another article, I am closing this as a duplicate.
Duplicate of #521

**Closed by edupont04** 2021-03-23 15:33 UTC
