### ISSUE TITLE
IMHO we need a real description of DEF

### ISSUE THREAD

**Issue by lvanvugt** [MicrosoftDocs/dynamics365smb-docs#300] opened 2020-02-21 05:33 UTC
The Data Exchange Framework has been around for quite some while, but, as it seems, it it not known by many developers. IMHO this is due to a lack of a good technical description of what is is and, even more, on how to make use of it. I.e. how to address it. This week I have been teaching people on it and had a hard time to everything in place myself. It is a great pity that DEF has never given the attention it needs.

BTW: in this topic DEF is more or less only approached from a functional perspective, i.e. it is discussing the features that are build on DEF. With all respect, that is not explaining what DEF is and how to use it. I deserves so much better.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 633f7be1-2925-08b7-28f2-d4712632a730
* Version Independent ID: 593ffd07-a994-7b69-11a6-385fefcf395a
* Content: [About the Data Exchange Framework - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/across-about-the-data-exchange-framework)
* Content Source: [business-central/across-about-the-data-exchange-framework.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/live/business-central/across-about-the-data-exchange-framework.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SorenGP
* Microsoft Alias: **sgroespe**

**Comment by lvanvugt** [comment] 2020-02-21 07:05
BTW: would be a pleasure to help on that.

**Comment by edupont04** [comment] 2020-07-24 15:54
Duplicate of #296

**Closed by edupont04** 2020-07-24 15:54 UTC
